# Generated by Django 3.2.4 on 2021-06-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210621_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockDataBase',
        ),
    ]
