# Generated by Django 3.2.4 on 2021-06-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_guest_house_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.house'),
        ),
        migrations.CreateModel(
            name='Relationer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resident')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='residents',
            field=models.ManyToManyField(through='main.Relationer', to='main.Resident'),
        ),
        migrations.AddField(
            model_name='resident',
            name='houses',
            field=models.ManyToManyField(through='main.Relationer', to='main.House'),
        ),
    ]
