# Generated by Django 3.2.4 on 2021-06-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210622_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='home',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
    ]
