# Generated by Django 3.2.4 on 2021-06-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_auto_20210622_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('special_note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('resident_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resident_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.guest')),
                ('residents', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.resident')),
            ],
        ),
    ]
