# Generated by Django 3.2.4 on 2021-06-28 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_guestlogmodel_time_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlogmodel',
            name='time_logged',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
