# Generated by Django 3.2.4 on 2021-06-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_guestlogmodel_time_logged'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestLogModel',
            new_name='GuestLog',
        ),
    ]
