# Generated by Django 3.2.4 on 2021-10-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_guestlog_time_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owner_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
