# Generated by Django 3.2.4 on 2021-10-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_house_owner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.house'),
        ),
    ]
