# Generated by Django 3.2.4 on 2021-10-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_guest_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
