# Generated by Django 3.2.4 on 2021-10-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20211003_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address_visiting',
            field=models.CharField(max_length=100),
        ),
    ]
