# Generated by Django 3.2.4 on 2021-10-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_guestlog_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
