# Generated by Django 3.2.4 on 2021-10-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_guestlog_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='special_note',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
