# Generated by Django 3.2.4 on 2021-10-29 03:24

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_guestlog_date_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='date_logged',
            field=models.DateTimeField(blank=True, default=time.localtime),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='time_logged',
            field=models.DateTimeField(blank=True, default=time.localtime),
        ),
    ]
