# Generated by Django 3.2.4 on 2021-10-29 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20211028_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='date_logged',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='time_logged',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
