# Generated by Django 3.2.4 on 2021-11-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_guestlog_special_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='special_note',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
