# Generated by Django 3.2.4 on 2021-06-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210622_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='residents',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='houses',
        ),
        migrations.AddField(
            model_name='resident',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.house'),
        ),
        migrations.DeleteModel(
            name='Relationer',
        ),
    ]
