# Generated by Django 3.2.4 on 2021-06-29 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_guestlogmodel_guestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlog',
            name='date_logged',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
