# Generated by Django 3.2.4 on 2021-10-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20211003_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='unit',
        ),
    ]
