# Generated by Django 3.2.4 on 2021-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20211003_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='unit',
        ),
        migrations.AlterField(
            model_name='guest',
            name='address_visiting',
            field=models.CharField(default='1310 4th st', max_length=100),
        ),
    ]
