# Generated by Django 3.2.4 on 2021-10-13 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_guest_address_visiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlog',
            name='unit',
        ),
        migrations.AddField(
            model_name='guestlog',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='date_logged',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
