# Generated by Django 3.2.4 on 2021-10-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_guestlog_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
