# Generated by Django 3.2.4 on 2021-10-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20211014_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='plate',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='guestlog',
            name='vehicle',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
