# Generated by Django 3.2.4 on 2021-10-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_guestlog_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlog',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
