# Generated by Django 3.2.4 on 2021-10-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20211030_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
