# Generated by Django 3.2.4 on 2021-10-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20211031_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owner_email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
